[package]
name = "risingwave_common_proc_macro"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true





[dependencies]
proc-macro-error = "1.0"
quote = "1"
proc-macro2 = { version = "1", default-features = false }
syn = "1"
bae = "0.1.7"
itertools = { workspace = true }

[lints]
workspace = true
