# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "workspace-hack"

# Format for `workspace-hack = ...` lines in other Cargo.tomls. Requires cargo-hakari 0.9.22 or above.
dep-format-version = "4"

# Setting workspace.resolver = "2" in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the new feature resolver.
# For more about the new feature resolver, see:
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver
resolver = "2"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    # "x86_64-unknown-linux-gnu",
    # "aarch64-unknown-linux-gnu",
    # "x86_64-apple-darwin",
    # "aarch64-apple-darwin",
]

# Write out exact versions rather than a semver range. (Defaults to false.)
# exact-versions = true

unify-target-host = "unify-if-both"

[traversal-excludes]
workspace-members = [
    "workspace-config",
    "risingwave_object_store",
    "risingwave_bench",
]
third-party = [
    { name = "opendal" },
    # For some reasons, tikv-jemalloc-sys would be compiled twice if being added into `workspace-hack`
    { name = "tikv-jemalloc-sys", git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9" },
    { name = "tikv-jemallocator", git = "https://github.com/risingwavelabs/jemallocator.git", rev = "64a2d9" },
    # These are solely dev-dependencies. Unifying them may slow down build.
    { name = "criterion" },
    { name = "console" },
    { name = "similar" },
    { name = "deltalake", git = "https://github.com/risingwavelabs/delta-rs", rev = "5c2dccd4640490202ffe98adbd13b09cef8e007b" },
]
