init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.test_all_delete',
]

slt = 'test_case/iceberg_source_all_delete.slt'

drop_sqls = [
    'DROP TABLE IF EXISTS demo_db.test_all_delete',
    'DROP SCHEMA IF EXISTS demo_db',
]