[package]
name = "risingwave-fields-derive"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }

[dev-dependencies]
expect-test = "1"
indoc = "2"
prettyplease = { version = "0.2", features = ["verbatim"] }
