[tasks.configure-if-not-configured]
private = true
condition = { env_not_set = [ "RISEDEV_CONFIGURED" ] }
script = '''
#!/usr/bin/env bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cargo run -p risedev-config -- -f "${ENV_PATH}" default
'''

[tasks.configure]
category = "RiseDev - Build"
description = "Configure what components to download/build"
script = '''
#!/usr/bin/env bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cargo run -p risedev-config -- -f "${ENV_PATH}" "$@"
'''
