init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.demo_table',
    '''
    CREATE TABLE demo_db.demo_table (
    id int,
    name string,
    description string
    ) USING iceberg
    TBLPROPERTIES ('format-version'='2');
    '''
]

slt = 'test_case/cdc/load.slt'

verify_schema = ['int','string','string']

verify_sql = 'SELECT * FROM demo_db.demo_table ORDER BY id ASC'

verify_data = """
101,101,101
102,102,102
103,103,103
104,104,104
105,105,105
106,106,106
107,107,107
108,108,108
"""

drop_sqls = []
