[package]
name = "sqlparser_bench"
version = "0.1.0"
authors = ["Dandandan <danielheres@gmail.com>"]
edition = "2018"





[dependencies]
risingwave_sqlparser = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "sqlparser_bench"
harness = false

[lints]
workspace = true
