name: License checker

on:
  push:
    branches:
    - main
    - "forks/*"
  pull_request:
    branches:
    - main
    - "v*.*.*-rc"
  merge_group:
    types: [checks_requested]
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v4
    - name: Check License Header
      uses: apache/skywalking-eyes@3ea9df11bb3a5a85665377d1fd10c02edecf2c40
